name: Secure RDP Setup (Optimized)

on:
  workflow_dispatch: # Memungkinkan trigger manual

jobs:
  secure-rdp:
    # Catatan: Runner standar 'windows-latest' memiliki 7 GB RAM.
    # Untuk RAM 128 GB, Anda memerlukan "GitHub-hosted larger runners"
    # yang merupakan fitur berbayar dan memerlukan pendaftaran.
    # Jika Anda memilikinya, ganti 'windows-latest' dengan 'windows-latest-16-cores' (64GB)
    # atau 'windows-latest-32-cores' (128GB).
    runs-on: windows-latest-32-cores
    
    # Timeout maksimum untuk job adalah 360 menit (6 jam).
    # 3600 (60 jam) tidak valid dan akan gagal.
    timeout-minutes: 360 

    steps:
    - name: Disable Windows Defender
      run: |
        Write-Host "Menonaktifkan Microsoft Defender..."
        Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableBehaviorMonitoring $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableBlockAtFirstSeen $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableIOAVProtection $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableScriptScanning $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableArchiveScanning $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableIntrusionPreventionSystem $true -ErrorAction SilentlyContinue
        Set-MpPreference -DisableCloudProtection $true -ErrorAction SilentlyContinue
        Write-Host "Microsoft Defender telah dinonaktifkan."

    - name: Configure Core RDP Settings
      run: |
        Write-Host "Mengkonfigurasi RDP..."
        # Mengaktifkan Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
          -Name "fDenyTSConnections" -Value 0 -Force
        
        # Menonaktifkan NLA (Network Level Authentication) untuk kompatibilitas
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
          -Name "UserAuthentication" -Value 0 -Force
        
        # Mengatur Security Layer ke 'Negotiate' (1) - lebih baik dari 'RDP' (0)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
          -Name "SecurityLayer" -Value 1 -Force
          
        # Konfigurasi firewall untuk RDP (Port 3389)
        # Hapus aturan lama jika ada, lalu tambahkan aturan baru
        netsh advfirewall firewall delete rule name="RDP-Tailscale" 2>$null
        netsh advfirewall firewall add rule name="RDP-Tailscale" `
          dir=in action=allow protocol=TCP localport=3389
          
        # Restart layanan RDP
        Restart-Service -Name TermService -Force
        Start-Service -Name SessionEnv -ErrorAction SilentlyContinue
        Write-Host "Konfigurasi RDP selesai."

    - name: Create RDP User with Fixed Password
      run: |
        $username = "RDP"
        $password = "Igede123456@" # Sesuai permintaan, password tidak diubah
        
        Write-Host "Membuat user RDP: $username"
        # Cek jika user sudah ada
        if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
          Write-Host "User $username sudah ada. Menghapus user lama..."
          Remove-LocalUser -Name $username -Confirm:$false
        }
        
        # Buat objek password yang aman
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force
        
        # Buat user baru
        New-LocalUser -Name $username -Password $securePass -AccountNeverExpires -PasswordNeverExpires -Description "RDP Access User"
        
        # Tambahkan ke grup Administrators dan Remote Desktop Users
        Add-LocalGroupMember -Group "Administrators" -Member $username
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
        
        # Aktifkan akun
        Enable-LocalUser -Name $username
        
        # Verifikasi
        if (Get-LocalUser -Name $username) {
          Write-Host "User $username berhasil dibuat."
          echo "RDP_USERNAME=$username" >> $env:GITHUB_ENV
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
        } else {
          Write-Error "Gagal membuat user"
          exit 1
        }

    - name: Install Tailscale
      run: |
        Write-Host "Mengunduh dan menginstal Tailscale..."
        $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
        $installerPath = "$env:TEMP\tailscale.msi"
        
        # Download dan install
        Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
        Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
        Remove-Item $installerPath -Force
        
        # Beri waktu sejenak untuk layanan Tailscale dimulai
        Write-Host "Menunggu instalasi Tailscale..."
        Start-Sleep -Seconds 10

    - name: Establish Tailscale Connection
      run: |
        Write-Host "Menyambungkan ke Tailscale..."
        # Buat hostname unik berdasarkan ID proses
        $hostname = "gh-rdp-$env:GITHUB_RUN_ID"
        
        # Path ke Tailscale.exe
        $tsPath = "$env:ProgramFiles\Tailscale\tailscale.exe"
        
        # Connect ke Tailscale
        & $tsPath up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=$hostname --accept-routes
        
        # Tunggu IP Tailscale (dengan timeout)
        $tsIP = $null
        $maxRetries = 15
        $retryCount = 0
        
        while (-not $tsIP -and $retryCount -lt $maxRetries) {
          Start-Sleep -Seconds 5
          $tsIP = & $tsPath ip -4
          $retryCount++
          Write-Host "Percobaan $retryCount/$maxRetries - IP: $tsIP"
        }
        
        if (-not $tsIP) {
          Write-Error "Gagal mendapatkan IP Tailscale setelah $maxRetries percobaan."
          & $tsPath status
          exit 1
        }
        
        echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
        echo "RDP_HOSTNAME=$hostname" >> $env:GITHUB_ENV
        Write-Host "Tailscale berhasil terhubung: $tsIP"

    - name: Verify RDP Accessibility
      run: |
        Write-Host "Memverifikasi konektivitas RDP..."
        Write-Host "Tailscale IP: $env:TAILSCALE_IP"
        Write-Host "Hostname: $env:RDP_HOSTNAME"
        
        # Tes RDP lokal
        $localTest = Test-NetConnection -ComputerName 127.0.0.1 -Port 3389 -WarningAction SilentlyContinue
        if (-not $localTest.TcpTestSucceeded) {
          Write-Warning "Layanan RDP lokal tidak merespon."
        }
        
        # Tes RDP via Tailscale
        $remoteTest = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389 -WarningAction SilentlyContinue
        if ($remoteTest.TcpTestSucceeded) {
          Write-Host "✅ Tes konektivitas RDP berhasil!"
        } else {
          Write-Warning "Tes konektivitas RDP gagal, namun workflow tetap dilanjutkan..."
        }

    - name: Display Connection Information
      run: |
        $border = "=" * 50
        Write-Host "`n$border"
        Write-Host " INFORMASI AKSES RDP"
        Write-Host "$border"
        Write-Host "Address (IP): $env:TAILSCALE_IP"
        Write-Host "Hostname:     $env:RDP_HOSTNAME"
        Write-Host "Username:     $env:RDP_USERNAME"
        Write-Host "Password:     $env:RDP_PASSWORD"
        Write-Host "$border"
        Write-Host "PENTING:"
        Write-Host "- Biarkan workflow ini tetap berjalan untuk menjaga akses"
        Write-Host "- Batalkan/Stop workflow jika sudah selesai"
        Write-Host "- Gunakan IP Tailscale di atas untuk koneksi RDP"
        Write-Host "$border`n"

    - name: Maintain Active Connection
      run: |
        # Loop ini menjaga agar job tetap berjalan
        $counter = 0
        while ($true) {
          $counter++
          $currentTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          Write-Host "[$currentTime] Sesi RDP Aktif - Siklus: $counter"
          Write-Host " ↳ IP: $env:TAILSCALE_IP | User: $env:RDP_USERNAME"
          
          # Cek status Tailscale setiap 15 menit (3 siklus * 300 detik)
          if ($counter % 3 -eq 0) {
            Write-Host " ↳ Memeriksa status Tailscale..."
            & "$env:ProgramFiles\Tailscale\tailscale.exe" status
          }
          
          # Interval keep-alive (5 menit)
          Start-Sleep -Seconds 300
        }
